import { RoleName } from './roles';

export const ACCESS_ROLES = {
  ADMIN_ONLY: ['Administrador'],
  VIEW_CORE_DATA: ['Administrador', 'Comercial', 'Soporte', 'Terreno'],
  MANAGE_PROSPECTS: ['Administrador', 'Comercial'],
  VERIFY_FEASIBILITY: ['Administrador', 'Soporte'],
  MANAGE_CUSTOMERS: ['Administrador', 'Comercial', 'Soporte'],
  MANAGE_SERVICES: ['Administrador', 'Comercial', 'Soporte'],
  CREATE_INSTALL_ORDER: ['Administrador', 'Comercial', 'Soporte'],
  VIEW_INVENTORY: ['Administrador', 'Soporte', 'Terreno', 'Inventario'],
  MANAGE_INVENTORY: ['Administrador', 'Soporte', 'Inventario'],
  INSTALL_EQUIPMENT: ['Administrador', 'Soporte', 'Terreno'],
  CREATE_TICKETS: ['Administrador', 'Comercial', 'Soporte'],
  MANAGE_TICKETS: ['Administrador', 'Soporte'],
  UPDATE_TICKET_STATUS: ['Administrador', 'Soporte', 'Terreno'],
  VIEW_WORK_ORDERS: ['Administrador', 'Comercial', 'Soporte', 'Terreno'],
  COMPLETE_INSTALLATION: ['Administrador', 'Soporte', 'Terreno'],
  VIEW_BILLING: ['Administrador', 'Comercial', 'Soporte'],
  MANAGE_BILLING: ['Administrador', 'Comercial'],
  MANAGE_PAYMENT_ZONES: ['Administrador', 'Comercial'],
  MANAGE_TVIP: ['Administrador', 'Comercial', 'Soporte'],
  VIEW_MONITORING: ['Administrador', 'Soporte', 'Terreno'],
  REGISTER_TECHNICAL_NOTES: ['Administrador', 'Soporte', 'Terreno'],
  MANAGE_PLANS: ['Administrador', 'Comercial'],
  MANAGE_CONTRACTS: ['Administrador', 'Comercial'],
  GENERATE_DIGITAL_CONTRACT: ['Administrador', 'Comercial'],
  CHANGE_CUSTOMER_PLAN: ['Administrador', 'Comercial'],
  MANAGE_OBSERVATIONS: ['Administrador', 'Comercial', 'Soporte', 'Terreno'],
  MANAGE_CUSTOMER_REQUESTS: ['Administrador', 'Comercial', 'Soporte'],
  MANAGE_EQUIPMENT_ASSIGNMENT_MODE: ['Administrador', 'Soporte', 'Terreno', 'Inventario'],
  VIEW_CONTROL_BOOK: ['Administrador', 'Comercial', 'Soporte'],
  EXPORT_CONTROL_BOOK: ['Administrador', 'Comercial'],
  MANAGE_COMMERCIAL_COLLECTIONS: ['Administrador', 'Comercial'],
  VIEW_G1_EQUIPMENT: ['Administrador', 'Comercial', 'Soporte'],
  MANAGE_G1_ACTIVATION_RETRY: ['Administrador', 'Soporte'],
  MANAGE_COMMERCIAL_WARRANTIES: ['Administrador', 'Comercial'],
} as const satisfies Record<string, readonly RoleName[]>;
