-- Proposed independently of G2. Do not apply until the owning team reviews it.
CREATE TABLE "tax_emission_intent" (
    "id_intencion" UUID NOT NULL,
    "id_empresa" INTEGER NOT NULL,
    "id_factura" INTEGER NOT NULL,
    "id_pago" INTEGER,
    "business_key" VARCHAR(120) NOT NULL,
    "policy_version" VARCHAR(64) NOT NULL,
    "ambiente" VARCHAR(20) NOT NULL,
    "proveedor" VARCHAR(30) NOT NULL DEFAULT 'FACTURACION_CL',
    "tipo_dte" INTEGER NOT NULL,
    "formato" INTEGER NOT NULL,
    "fingerprint" CHAR(64) NOT NULL,
    "folio_esperado" VARCHAR(10) NOT NULL,
    "estado" VARCHAR(30) NOT NULL DEFAULT 'PENDIENTE',
    "intentos" INTEGER NOT NULL DEFAULT 0,
    "claim_id" UUID,
    "folio" VARCHAR(10),
    "ultimo_error" VARCHAR(64),
    "fecha_creacion" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "fecha_inicio" TIMESTAMPTZ(3),
    "fecha_envio" TIMESTAMPTZ(3),
    "fecha_actualizacion" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "tax_emission_intent_pkey" PRIMARY KEY ("id_intencion"),
    CONSTRAINT "tax_intent_company_fk" FOREIGN KEY ("id_empresa") REFERENCES "empresa"("id_empresa") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "tax_intent_invoice_fk" FOREIGN KEY ("id_factura") REFERENCES "factura"("id_factura") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "tax_intent_payment_fk" FOREIGN KEY ("id_pago") REFERENCES "pago"("id_pago") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "tax_intent_environment_check" CHECK ("ambiente" IN ('sandbox', 'production')),
    CONSTRAINT "tax_intent_provider_check" CHECK ("proveedor" = 'FACTURACION_CL'),
    CONSTRAINT "tax_intent_type_check" CHECK ("tipo_dte" IN (33, 34, 39, 41)),
    CONSTRAINT "tax_intent_format_check" CHECK (("tipo_dte" IN (33, 34) AND "formato" = 2) OR ("tipo_dte" IN (39, 41) AND "formato" = 1)),
    CONSTRAINT "tax_intent_fingerprint_check" CHECK ("fingerprint" ~ '^[a-f0-9]{64}$'),
    CONSTRAINT "tax_intent_expected_folio_check" CHECK ("folio_esperado" ~ '^[1-9][0-9]{0,9}$'),
    CONSTRAINT "tax_intent_state_check" CHECK ("estado" IN ('PENDIENTE', 'EN_PROCESO', 'GENERADO', 'FALLIDO', 'RESULTADO_INDETERMINADO')),
    CONSTRAINT "tax_intent_attempts_check" CHECK ("intentos" >= 0),
    CONSTRAINT "tax_intent_claim_check" CHECK ("estado" <> 'EN_PROCESO' OR ("claim_id" IS NOT NULL AND "fecha_inicio" IS NOT NULL)),
    CONSTRAINT "tax_intent_generated_check" CHECK ("estado" <> 'GENERADO' OR ("folio" IS NOT NULL AND "folio" = "folio_esperado"))
);
CREATE UNIQUE INDEX "tax_emission_intent_id_empresa_ambiente_business_key_key" ON "tax_emission_intent"("id_empresa", "ambiente", "business_key");
CREATE INDEX "tax_emission_intent_id_empresa_estado_fecha_actualizacion_idx" ON "tax_emission_intent"("id_empresa", "estado", "fecha_actualizacion");
